import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

export const BASE_ROLES = [
  'platform_owner',
  'platform_admin',
  'platform_support',
  'platform_auditor',
  'developer_owner',
  'developer_admin',
  'developer_sales_manager',
  'developer_sales_agent',
  'brokerage_owner',
  'brokerage_admin',
  'broker',
  'individual_broker',
  'client',
] as const;

export const BASE_PERMISSIONS = [
  'organizations.verify',
  'organizations.suspend',
  'organizations.view_all',
  'platform.settings',
  'subscriptions.manage',
  'disputes.resolve',
  'audit_logs.view',
  'reports.platform_wide',
  'users.impersonate',
  'organizations.update',
  'organizations.update_own',
  'users.manage',
  'users.manage_own_org',
  'projects.create',
  'projects.publish',
  'projects.edit',
  'inventory.create',
  'inventory.publish',
  'inventory.view_private',
  'commission_rules.manage',
  'broker_access.grant',
  'reservation_requests.approve',
  'deal_rooms.create',
  'deal_rooms.join',
  'deals.approve',
  'deals.mark_sold',
  'commissions.view',
  'commissions.approve',
  'brokerage_agreements.manage',
  'reports.developer',
  'marketplace.view',
  'inventory.view_approved',
  'lead_claims.create',
  'lead_claims.view_own',
  'deal_requests.create',
  'commissions.view_own',
  'organization_website.update_own',
  'organization_website.view_own',
  'organization_domains.manage_own',
  'organization_domains.view_own',
  'organization_domains.verify',
  'public_leads.view_own',
  'public_leads.manage_own',
  'public_leads.view_all',
  'public_leads.manage_all',
  'crm.leads.view_own',
  'crm.leads.manage_own',
  'crm.leads.claim',
  'crm.conversations.view_own',
  'crm.conversations.manage_own',
  'crm.conversations.view_project',
  'crm.clients.view_own',
  'crm.clients.manage_own',
  'crm.pipeline.view_own',
  'crm.pipeline.manage_own',
  'crm.notes.view_own',
  'crm.notes.manage_own',
  'crm.tasks.view_own',
  'crm.tasks.manage_own',
  'hr.view',
  'hr.manage',
  'hr.attendance.manage',
  'accounting.view',
  'accounting.manage',
  'legal.view',
  'legal.manage',
  'ads.view',
  'ads.manage',
  'cameras.view',
  'cameras.manage',
  'imports.project_inventory',
  'imports.hr',
  'imports.accounting',
  'imports.legal',
  'imports.ads',
  'imports.cameras',
  'exports.organization_data',
  'exports.platform_data',
  'brokers.manage',
  'reports.brokerage',
  'reports.own',
  'disputes.raise',
] as const;

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  platform_owner: [
    'organizations.verify',
    'organizations.suspend',
    'organizations.view_all',
    'organizations.update',
    'platform.settings',
    'subscriptions.manage',
    'disputes.resolve',
    'audit_logs.view',
    'reports.platform_wide',
    'users.impersonate',
    'users.manage',
    'organization_website.update_own',
    'organization_website.view_own',
    'organization_domains.manage_own',
    'organization_domains.view_own',
    'organization_domains.verify',
    'public_leads.view_own',
    'public_leads.manage_own',
    'public_leads.view_all',
    'public_leads.manage_all',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'crm.pipeline.view_own',
    'crm.pipeline.manage_own',
    'crm.notes.view_own',
    'crm.notes.manage_own',
    'crm.tasks.view_own',
    'crm.tasks.manage_own',
    'hr.view',
    'hr.manage',
    'hr.attendance.manage',
    'accounting.view',
    'accounting.manage',
    'legal.view',
    'legal.manage',
    'ads.view',
    'ads.manage',
    'cameras.view',
    'cameras.manage',
    'imports.project_inventory',
    'imports.hr',
    'imports.accounting',
    'imports.legal',
    'imports.ads',
    'imports.cameras',
    'deal_rooms.join',
    'exports.organization_data',
    'exports.platform_data',
  ],
  platform_admin: [
    'organizations.verify',
    'organizations.suspend',
    'organizations.view_all',
    'organizations.update',
    'subscriptions.manage',
    'disputes.resolve',
    'audit_logs.view',
    'reports.platform_wide',
    'users.manage',
    'organization_website.update_own',
    'organization_website.view_own',
    'organization_domains.manage_own',
    'organization_domains.view_own',
    'organization_domains.verify',
    'public_leads.view_own',
    'public_leads.manage_own',
    'public_leads.view_all',
    'public_leads.manage_all',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'crm.pipeline.view_own',
    'crm.pipeline.manage_own',
    'crm.notes.view_own',
    'crm.notes.manage_own',
    'crm.tasks.view_own',
    'crm.tasks.manage_own',
    'hr.view',
    'hr.manage',
    'hr.attendance.manage',
    'accounting.view',
    'accounting.manage',
    'legal.view',
    'legal.manage',
    'ads.view',
    'ads.manage',
    'cameras.view',
    'cameras.manage',
    'imports.project_inventory',
    'imports.hr',
    'imports.accounting',
    'imports.legal',
    'imports.ads',
    'imports.cameras',
    'deal_rooms.join',
    'exports.organization_data',
    'exports.platform_data',
  ],
  platform_support: [
    'organizations.view_all',
    'audit_logs.view',
    'disputes.resolve',
  ],
  platform_auditor: [
    'organizations.view_all',
    'audit_logs.view',
    'reports.platform_wide',
  ],
  developer_owner: [
    'organizations.update_own',
    'users.manage_own_org',
    'organization_website.update_own',
    'organization_website.view_own',
    'organization_domains.manage_own',
    'organization_domains.view_own',
    'public_leads.view_own',
    'public_leads.manage_own',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'crm.pipeline.view_own',
    'crm.pipeline.manage_own',
    'crm.notes.view_own',
    'crm.notes.manage_own',
    'crm.tasks.view_own',
    'crm.tasks.manage_own',
    'hr.view',
    'hr.manage',
    'hr.attendance.manage',
    'accounting.view',
    'accounting.manage',
    'legal.view',
    'legal.manage',
    'ads.view',
    'ads.manage',
    'cameras.view',
    'cameras.manage',
    'imports.project_inventory',
    'imports.hr',
    'imports.accounting',
    'imports.legal',
    'imports.ads',
    'imports.cameras',
    'exports.organization_data',
    'projects.create',
    'projects.publish',
    'projects.edit',
    'inventory.create',
    'inventory.publish',
    'inventory.view_private',
    'commission_rules.manage',
    'broker_access.grant',
    'reservation_requests.approve',
    'deal_rooms.create',
    'deal_rooms.join',
    'deals.approve',
    'deals.mark_sold',
    'commissions.view',
    'commissions.approve',
    'brokerage_agreements.manage',
    'reports.developer',
  ],
  developer_admin: [
    'organizations.update_own',
    'users.manage_own_org',
    'organization_website.update_own',
    'organization_website.view_own',
    'organization_domains.manage_own',
    'organization_domains.view_own',
    'public_leads.view_own',
    'public_leads.manage_own',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'imports.project_inventory',
    'imports.hr',
    'imports.accounting',
    'imports.legal',
    'imports.ads',
    'imports.cameras',
    'exports.organization_data',
    'projects.create',
    'projects.publish',
    'projects.edit',
    'inventory.create',
    'inventory.publish',
    'inventory.view_private',
    'broker_access.grant',
    'reservation_requests.approve',
    'deal_rooms.create',
    'deal_rooms.join',
    'deals.approve',
    'commissions.view',
    'reports.developer',
    'crm.leads.view_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
    'exports.organization_data',
  ],
  developer_sales_manager: [
    'projects.edit',
    'inventory.view_private',
    'reservation_requests.approve',
    'deal_rooms.create',
    'deal_rooms.join',
    'deals.approve',
    'deals.mark_sold',
    'commissions.view',
    'reports.developer',
  ],
  developer_sales_agent: [
    'inventory.view_private',
    'deal_rooms.join',
    'reports.own',
    'exports.organization_data',
    'crm.leads.view_own',
    'crm.conversations.view_project',
    'crm.clients.view_own',
  ],
  brokerage_owner: [
    'organizations.update_own',
    'users.manage_own_org',
    'organization_website.view_own',
    'organization_domains.view_own',
    'organization_domains.manage_own',
    'public_leads.view_own',
    'public_leads.manage_own',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'crm.pipeline.view_own',
    'crm.pipeline.manage_own',
    'crm.notes.view_own',
    'crm.notes.manage_own',
    'crm.tasks.view_own',
    'crm.tasks.manage_own',
    'exports.organization_data',
    'marketplace.view',
    'inventory.view_approved',
    'lead_claims.create',
    'lead_claims.view_own',
    'deal_requests.create',
    'deal_rooms.join',
    'commissions.view_own',
    'brokers.manage',
    'reports.brokerage',
    'disputes.raise',
  ],
  brokerage_admin: [
    'organizations.update_own',
    'users.manage_own_org',
    'organization_website.view_own',
    'organization_domains.view_own',
    'organization_domains.manage_own',
    'public_leads.view_own',
    'public_leads.manage_own',
    'crm.leads.view_own',
    'crm.leads.manage_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.clients.view_own',
    'crm.clients.manage_own',
    'crm.pipeline.view_own',
    'crm.pipeline.manage_own',
    'crm.notes.view_own',
    'crm.notes.manage_own',
    'crm.tasks.view_own',
    'crm.tasks.manage_own',
    'exports.organization_data',
    'marketplace.view',
    'inventory.view_approved',
    'lead_claims.view_own',
    'deal_rooms.join',
    'commissions.view_own',
    'brokers.manage',
    'reports.brokerage',
    'disputes.raise',
  ],
  broker: [
    'marketplace.view',
    'inventory.view_approved',
    'lead_claims.create',
    'lead_claims.view_own',
    'deal_requests.create',
    'deal_rooms.join',
    'commissions.view_own',
    'reports.own',
    'disputes.raise',
    'crm.leads.view_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.clients.view_own',
  ],
  individual_broker: [
    'marketplace.view',
    'inventory.view_approved',
    'lead_claims.create',
    'lead_claims.view_own',
    'deal_requests.create',
    'deal_rooms.join',
    'commissions.view_own',
    'reports.own',
    'disputes.raise',
    'crm.leads.view_own',
    'crm.leads.claim',
    'crm.conversations.view_own',
    'crm.conversations.manage_own',
    'crm.clients.view_own',
  ],
  client: ['deal_rooms.join'],
};

export async function seedBaseRolesAndPermissions(prisma: PrismaClient) {
  let permissionsSeeded = 0;
  let rolesSeeded = 0;

  for (const key of BASE_PERMISSIONS) {
    await prisma.permission.upsert({
      where: { key },
      create: { key, description: `Base permission: ${key}` },
      update: {},
    });
    permissionsSeeded += 1;
  }

  for (const name of BASE_ROLES) {
    const existingRole = await prisma.role.findFirst({
      where: { organizationId: null, name },
    });
    const systemRole = existingRole
      ? await prisma.role.update({
          where: { id: existingRole.id },
          data: { isSystem: true },
        })
      : await prisma.role.create({
          data: {
            name,
            isSystem: true,
            description: `Base system role: ${name}`,
          },
        });
    rolesSeeded += 1;

    const rolesToSync = await prisma.role.findMany({ where: { name } });
    const uniqueRoles = new Map(
      [systemRole, ...rolesToSync].map((role) => [role.id, role]),
    );

    for (const role of uniqueRoles.values()) {
      await syncRolePermissions(prisma, role.id, name);
    }
  }

  return { rolesSeeded, permissionsSeeded };
}

async function syncRolePermissions(
  prisma: Pick<PrismaClient, 'permission' | 'rolePermission'>,
  roleId: string,
  roleName: (typeof BASE_ROLES)[number],
) {
  for (const permissionKey of ROLE_PERMISSIONS[roleName]) {
    const permission = await prisma.permission.findUniqueOrThrow({
      where: { key: permissionKey },
    });

    await prisma.rolePermission.upsert({
      where: {
        roleId_permissionId: {
          roleId,
          permissionId: permission.id,
        },
      },
      create: {
        roleId,
        permissionId: permission.id,
      },
      update: {},
    });
  }
}

if (require.main === module) {
  const connectionString =
    process.env.DATABASE_URL ??
    'postgresql://postgres:postgres@localhost:5432/popwam?schema=public';
  const adapter = new PrismaPg({ connectionString });
  const prisma = new PrismaClient({ adapter });

  seedBaseRolesAndPermissions(prisma)
    .then((result) => {
      console.log(JSON.stringify(result));
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
