import Link from "next/link";
import { ArrowUpRight, Building2, CalendarDays, MessageSquareText, UsersRound } from "lucide-react";
import { ConversationStatusBadge, PreferredContactMethodBadge } from "@/components/admin-crm/badges";
import { EmptyState } from "@/components/empty-state";
import { formatDate } from "@/lib/format";
import type { Conversation, ConversationMessage } from "@/types/admin-crm";

export function ConversationResponsiveList({ conversations, basePath }: { conversations: Conversation[]; basePath: string }) {
  if (!conversations.length) return <EmptyState icon={<MessageSquareText className="h-5 w-5" aria-hidden="true" />} title="No conversations match this view" description="New lead conversations will appear here when they are created." />;

  return <div className="divide-y divide-[var(--color-border)] overflow-hidden rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)]">{conversations.map((conversation) => { const recent = latestMessage(conversation.recentMessages); const title = conversation.crmLead?.client?.name ?? conversation.project?.name ?? formatLabel(conversation.type); return <article key={conversation.id} className="p-4 transition hover:bg-[var(--color-surface-muted)] sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[var(--color-accent-soft)] text-sm font-bold text-[var(--color-accent)]">{initials(title)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-semibold text-[var(--color-foreground)]">{title}</h2><ConversationStatusBadge status={conversation.status} /><span className="ui-badge">{formatLabel(conversation.type)}</span></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--color-muted)]">{recent?.body ?? "No messages yet. Open the conversation to start the discussion."}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[var(--color-muted)]">{conversation.project?.name ? <span className="inline-flex items-center gap-1.5"><Building2 className="h-3.5 w-3.5" aria-hidden="true" />{conversation.project.name}</span> : null}<span className="inline-flex items-center gap-1.5"><UsersRound className="h-3.5 w-3.5" aria-hidden="true" />{participantSummary(conversation)}</span><span className="inline-flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" aria-hidden="true" />Updated {formatDate(conversation.updatedAt)}</span></div></div></div><div className="flex shrink-0 items-center gap-3"><PreferredContactMethodBadge method={conversation.crmLead?.preferredContactMethod} /><Link href={`${basePath}/${conversation.id}`} className="ui-button ui-button-secondary">Open conversation<ArrowUpRight className="h-4 w-4" aria-hidden="true" /></Link></div></div></article>; })}</div>;
}

function latestMessage(messages?: ConversationMessage[]) { return [...(messages ?? [])].sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()).at(-1); }
function participantSummary(conversation: Conversation) { const participants = conversation.participants ?? []; return participants.length ? participants.slice(0, 3).map((participant) => participant.displayName || formatLabel(participant.publicRole)).join(", ") : "Participants not returned"; }
function initials(value: string) { return value.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "C"; }
function formatLabel(value: string) { return value.toLowerCase().split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
