export const EMPLOYEE_ROLE_OPTIONS = [
  "platform_support",
  "platform_hr",
  "platform_sales",
  "platform_admin_limited",
  "company_admin",
  "hr_manager",
  "hr_employee",
  "sales_manager",
  "sales_agent",
  "finance_user",
  "employee_self_service",
] as const;

export const EMPLOYEE_PERMISSION_GROUPS = [
  {
    id: "dashboard",
    labelKey: "employeeAccess.group.dashboard",
    permissions: ["company.dashboard.view"],
  },
  {
    id: "employees",
    labelKey: "employeeAccess.group.employees",
    permissions: [
      "hr.employees.view",
      "hr.employees.create",
      "hr.employees.update",
      "hr.employees.delete",
      "hr.employees.deactivate",
      "hr.employees.reset_password",
      "hr.employees.permissions.manage",
    ],
  },
  {
    id: "workGroups",
    labelKey: "employeeAccess.group.workGroups",
    permissions: ["hr.work_groups.view", "hr.work_groups.manage"],
  },
  {
    id: "teams",
    labelKey: "employeeAccess.group.teams",
    permissions: ["hr.teams.view", "hr.teams.manage"],
  },
  {
    id: "actions",
    labelKey: "employeeAccess.group.actions",
    permissions: ["hr.actions.view", "hr.actions.apply"],
  },
  {
    id: "documents",
    labelKey: "employeeAccess.group.documents",
    permissions: ["hr.documents.view", "hr.documents.manage", "hr.hr_documents.view", "hr.hr_documents.manage"],
  },
  {
    id: "orgChart",
    labelKey: "employeeAccess.group.orgChart",
    permissions: ["hr.org_chart.view", "hr.transfer_log.view", "hr.title_changes.view"],
  },
  {
    id: "attendance",
    labelKey: "employeeAccess.group.attendance",
    permissions: [
      "hr.attendance.self",
      "hr.attendance.view",
      "hr.attendance.manage",
      "hr.attendance.review",
      "hr.attendance.export",
    ],
  },
  {
    id: "requests",
    labelKey: "employeeAccess.group.requests",
    permissions: ["hr.requests.view", "hr.requests.manage"],
  },
  {
    id: "finance",
    labelKey: "employeeAccess.group.finance",
    permissions: ["hr.finance.view", "hr.finance.manage"],
  },
  {
    id: "assets",
    labelKey: "employeeAccess.group.assets",
    permissions: ["hr.assets.view", "hr.assets.manage"],
  },
  {
    id: "tasks",
    labelKey: "employeeAccess.group.tasks",
    permissions: ["hr.tasks.view", "hr.tasks.manage"],
  },
  {
    id: "crm",
    labelKey: "employeeAccess.group.crm",
    permissions: ["crm.leads.view", "crm.leads.create", "crm.leads.update", "crm.leads.assign"],
  },
  {
    id: "deals",
    labelKey: "employeeAccess.group.deals",
    permissions: ["deals.view", "deals.create", "deals.update", "deals.manage"],
  },
  {
    id: "dealRooms",
    labelKey: "employeeAccess.group.dealRooms",
    permissions: ["deal_rooms.join", "deal_rooms.create", "deal_rooms.manage"],
  },
  {
    id: "files",
    labelKey: "employeeAccess.group.files",
    permissions: ["files.view", "files.upload"],
  },
  {
    id: "reports",
    labelKey: "employeeAccess.group.reports",
    permissions: ["reports.view", "reports.export", "hr.reports.view", "hr.reports.export"],
  },
  {
    id: "settings",
    labelKey: "employeeAccess.group.settings",
    permissions: ["company.settings.view", "company.settings.manage", "hr.settings.view", "hr.settings.manage"],
  },
  {
    id: "platform",
    labelKey: "employeeAccess.group.platform",
    platformOnly: true,
    permissions: ["platform.organizations.view", "platform.organizations.manage", "platform.users.manage"],
  },
] as const;

export const PERMISSION_LABEL_KEYS: Record<string, string> = {
  "company.dashboard.view": "employeeAccess.permission.companyDashboardView",
  "company.settings.view": "employeeAccess.permission.companySettingsView",
  "company.settings.manage": "employeeAccess.permission.companySettingsManage",
  "hr.employees.view": "employeeAccess.permission.hrEmployeesView",
  "hr.employees.create": "employeeAccess.permission.hrEmployeesCreate",
  "hr.employees.update": "employeeAccess.permission.hrEmployeesUpdate",
  "hr.employees.delete": "employeeAccess.permission.hrEmployeesDelete",
  "hr.employees.deactivate": "employeeAccess.permission.hrEmployeesDeactivate",
  "hr.employees.reset_password": "employeeAccess.permission.hrEmployeesResetPassword",
  "hr.employees.permissions.manage": "employeeAccess.permission.hrEmployeesPermissionsManage",
  "hr.work_groups.view": "employeeAccess.permission.hrWorkGroupsView",
  "hr.work_groups.manage": "employeeAccess.permission.hrWorkGroupsManage",
  "hr.teams.view": "employeeAccess.permission.hrTeamsView",
  "hr.teams.manage": "employeeAccess.permission.hrTeamsManage",
  "hr.actions.view": "employeeAccess.permission.hrActionsView",
  "hr.actions.apply": "employeeAccess.permission.hrActionsApply",
  "hr.documents.view": "employeeAccess.permission.hrDocumentsView",
  "hr.documents.manage": "employeeAccess.permission.hrDocumentsManage",
  "hr.org_chart.view": "employeeAccess.permission.hrOrgChartView",
  "hr.transfer_log.view": "employeeAccess.permission.hrTransferLogView",
  "hr.title_changes.view": "employeeAccess.permission.hrTitleChangesView",
  "hr.requests.view": "employeeAccess.permission.hrRequestsView",
  "hr.requests.manage": "employeeAccess.permission.hrRequestsManage",
  "hr.attendance.self": "employeeAccess.permission.hrAttendanceSelf",
  "hr.attendance.view": "employeeAccess.permission.hrAttendanceView",
  "hr.attendance.manage": "employeeAccess.permission.hrAttendanceManage",
  "hr.attendance.review": "employeeAccess.permission.hrAttendanceReview",
  "hr.attendance.export": "employeeAccess.permission.hrAttendanceExport",
  "hr.finance.view": "employeeAccess.permission.hrFinanceView",
  "hr.finance.manage": "employeeAccess.permission.hrFinanceManage",
  "hr.assets.view": "employeeAccess.permission.hrAssetsView",
  "hr.assets.manage": "employeeAccess.permission.hrAssetsManage",
  "hr.tasks.view": "employeeAccess.permission.hrTasksView",
  "hr.tasks.manage": "employeeAccess.permission.hrTasksManage",
  "hr.hr_documents.view": "employeeAccess.permission.hrHrDocumentsView",
  "hr.hr_documents.manage": "employeeAccess.permission.hrHrDocumentsManage",
  "hr.reports.view": "employeeAccess.permission.hrReportsView",
  "hr.reports.export": "employeeAccess.permission.hrReportsExport",
  "hr.settings.view": "employeeAccess.permission.hrSettingsView",
  "hr.settings.manage": "employeeAccess.permission.hrSettingsManage",
  "crm.leads.view": "employeeAccess.permission.crmLeadsView",
  "crm.leads.create": "employeeAccess.permission.crmLeadsCreate",
  "crm.leads.update": "employeeAccess.permission.crmLeadsUpdate",
  "crm.leads.assign": "employeeAccess.permission.crmLeadsAssign",
  "deals.view": "employeeAccess.permission.dealsView",
  "deals.create": "employeeAccess.permission.dealsCreate",
  "deals.update": "employeeAccess.permission.dealsUpdate",
  "deals.manage": "employeeAccess.permission.dealsManage",
  "deal_rooms.join": "employeeAccess.permission.dealRoomsJoin",
  "deal_rooms.create": "employeeAccess.permission.dealRoomsCreate",
  "deal_rooms.manage": "employeeAccess.permission.dealRoomsManage",
  "files.view": "employeeAccess.permission.filesView",
  "files.upload": "employeeAccess.permission.filesUpload",
  "reports.view": "employeeAccess.permission.reportsView",
  "reports.export": "employeeAccess.permission.reportsExport",
  "platform.organizations.view": "employeeAccess.permission.platformOrganizationsView",
  "platform.organizations.manage": "employeeAccess.permission.platformOrganizationsManage",
  "platform.users.manage": "employeeAccess.permission.platformUsersManage",
};
