export const EMPLOYEE_ROLE_OPTIONS = [
  "platform_support",
  "platform_hr",
  "platform_sales",
  "platform_admin_limited",
  "company_admin",
  "hr_manager",
  "hr_employee",
  "sales_manager",
  "sales_agent",
  "finance_user",
  "employee_self_service",
] as const;

export const EMPLOYEE_PERMISSION_GROUPS = [
  {
    id: "dashboard",
    labelKey: "employeeAccess.group.dashboard",
    permissions: ["company.dashboard.view"],
  },
  {
    id: "employees",
    labelKey: "employeeAccess.group.employees",
    permissions: [
      "hr.employees.view",
      "hr.employees.create",
      "hr.employees.update",
      "hr.employees.deactivate",
      "hr.employees.reset_password",
      "hr.employees.permissions.manage",
    ],
  },
  {
    id: "attendance",
    labelKey: "employeeAccess.group.attendance",
    permissions: [
      "hr.attendance.self",
      "hr.attendance.view",
      "hr.attendance.manage",
      "hr.attendance.review",
      "hr.attendance.export",
    ],
  },
  {
    id: "crm",
    labelKey: "employeeAccess.group.crm",
    permissions: ["crm.leads.view", "crm.leads.create", "crm.leads.update", "crm.leads.assign"],
  },
  {
    id: "deals",
    labelKey: "employeeAccess.group.deals",
    permissions: ["deals.view", "deals.create", "deals.update", "deals.manage"],
  },
  {
    id: "dealRooms",
    labelKey: "employeeAccess.group.dealRooms",
    permissions: ["deal_rooms.join", "deal_rooms.create", "deal_rooms.manage"],
  },
  {
    id: "files",
    labelKey: "employeeAccess.group.files",
    permissions: ["files.view", "files.upload"],
  },
  {
    id: "reports",
    labelKey: "employeeAccess.group.reports",
    permissions: ["reports.view", "reports.export"],
  },
  {
    id: "settings",
    labelKey: "employeeAccess.group.settings",
    permissions: ["company.settings.view", "company.settings.manage"],
  },
  {
    id: "platform",
    labelKey: "employeeAccess.group.platform",
    platformOnly: true,
    permissions: ["platform.organizations.view", "platform.organizations.manage", "platform.users.manage"],
  },
] as const;

export const PERMISSION_LABEL_KEYS: Record<string, string> = {
  "company.dashboard.view": "employeeAccess.permission.companyDashboardView",
  "company.settings.view": "employeeAccess.permission.companySettingsView",
  "company.settings.manage": "employeeAccess.permission.companySettingsManage",
  "hr.employees.view": "employeeAccess.permission.hrEmployeesView",
  "hr.employees.create": "employeeAccess.permission.hrEmployeesCreate",
  "hr.employees.update": "employeeAccess.permission.hrEmployeesUpdate",
  "hr.employees.deactivate": "employeeAccess.permission.hrEmployeesDeactivate",
  "hr.employees.reset_password": "employeeAccess.permission.hrEmployeesResetPassword",
  "hr.employees.permissions.manage": "employeeAccess.permission.hrEmployeesPermissionsManage",
  "hr.attendance.self": "employeeAccess.permission.hrAttendanceSelf",
  "hr.attendance.view": "employeeAccess.permission.hrAttendanceView",
  "hr.attendance.manage": "employeeAccess.permission.hrAttendanceManage",
  "hr.attendance.review": "employeeAccess.permission.hrAttendanceReview",
  "hr.attendance.export": "employeeAccess.permission.hrAttendanceExport",
  "crm.leads.view": "employeeAccess.permission.crmLeadsView",
  "crm.leads.create": "employeeAccess.permission.crmLeadsCreate",
  "crm.leads.update": "employeeAccess.permission.crmLeadsUpdate",
  "crm.leads.assign": "employeeAccess.permission.crmLeadsAssign",
  "deals.view": "employeeAccess.permission.dealsView",
  "deals.create": "employeeAccess.permission.dealsCreate",
  "deals.update": "employeeAccess.permission.dealsUpdate",
  "deals.manage": "employeeAccess.permission.dealsManage",
  "deal_rooms.join": "employeeAccess.permission.dealRoomsJoin",
  "deal_rooms.create": "employeeAccess.permission.dealRoomsCreate",
  "deal_rooms.manage": "employeeAccess.permission.dealRoomsManage",
  "files.view": "employeeAccess.permission.filesView",
  "files.upload": "employeeAccess.permission.filesUpload",
  "reports.view": "employeeAccess.permission.reportsView",
  "reports.export": "employeeAccess.permission.reportsExport",
  "platform.organizations.view": "employeeAccess.permission.platformOrganizationsView",
  "platform.organizations.manage": "employeeAccess.permission.platformOrganizationsManage",
  "platform.users.manage": "employeeAccess.permission.platformUsersManage",
};
