ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'DOCUMENTS_REQUIRED';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'DOCUMENTS_UPLOADED';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'EXTRACTION_PENDING';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'MANUAL_REVIEW_REQUIRED';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'VERIFIED';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "OrganizationStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
